apiVersion: v1
kind: Service
metadata:
  name: nodeport-service-host
spec:
  type: NodePort
  selector:
    app: jenkins-host
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30081
